- name: Check Tomcat service is running
  systemd:
    name: tomcat
    state: started
  register: tomcat_service
  retries: 5
  delay: 5
  until: tomcat_service.state == "started"

- name: Check Tomcat Status
  uri:
    url: http://localhost:8080/
    status_code: 200
  register: tomcat_status
  retries: 5
  delay: 5
  until: tomcat_status.status == 200

